export { default as AboutPage } from './AboutPage';
export { default as SignInPage } from './SignInPage';
export { default as ContactPage } from './ContactPage';
export { default as ContactDetailsPage } from './ContactDetailsPage';
export { default as CreactContactPage } from './CreactContactPage';
export { default as NotFoundPage } from './NotFoundPage';
export { default as PortfolioPage} from './PortfolioPage';
export { default as TimelinePage} from './TimelinePage';
export { default as SignUpPage} from './SignUpPage';
export { default as UserPage} from './UserPage';